// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace rectangle_app.Migrations
{
    [DbContext(typeof(RectangleContext))]
    [Migration("20231114141042_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("Rectangle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.Property<int>("X")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Y")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Rectangles");

                    b.HasData(
                        new
                        {
                            Id = 201,
                            Height = 72,
                            Width = 97,
                            X = 12,
                            Y = 12
                        },
                        new
                        {
                            Id = 202,
                            Height = 71,
                            Width = 48,
                            X = 11,
                            Y = 4
                        },
                        new
                        {
                            Id = 203,
                            Height = 51,
                            Width = 86,
                            X = 16,
                            Y = 3
                        },
                        new
                        {
                            Id = 204,
                            Height = 61,
                            Width = 83,
                            X = 0,
                            Y = 10
                        },
                        new
                        {
                            Id = 205,
                            Height = 75,
                            Width = 3,
                            X = 15,
                            Y = 16
                        },
                        new
                        {
                            Id = 206,
                            Height = 83,
                            Width = 76,
                            X = 3,
                            Y = 16
                        },
                        new
                        {
                            Id = 207,
                            Height = 23,
                            Width = 81,
                            X = 13,
                            Y = 5
                        },
                        new
                        {
                            Id = 208,
                            Height = 49,
                            Width = 82,
                            X = 5,
                            Y = 7
                        },
                        new
                        {
                            Id = 209,
                            Height = 57,
                            Width = 91,
                            X = 13,
                            Y = 3
                        },
                        new
                        {
                            Id = 210,
                            Height = 19,
                            Width = 65,
                            X = 2,
                            Y = 0
                        },
                        new
                        {
                            Id = 211,
                            Height = 73,
                            Width = 21,
                            X = 8,
                            Y = 16
                        },
                        new
                        {
                            Id = 212,
                            Height = 9,
                            Width = 47,
                            X = 3,
                            Y = 0
                        },
                        new
                        {
                            Id = 213,
                            Height = 32,
                            Width = 15,
                            X = 20,
                            Y = 3
                        },
                        new
                        {
                            Id = 214,
                            Height = 46,
                            Width = 85,
                            X = 7,
                            Y = 3
                        },
                        new
                        {
                            Id = 215,
                            Height = 57,
                            Width = 47,
                            X = 8,
                            Y = 13
                        },
                        new
                        {
                            Id = 216,
                            Height = 79,
                            Width = 89,
                            X = 16,
                            Y = 8
                        },
                        new
                        {
                            Id = 217,
                            Height = 13,
                            Width = 18,
                            X = 14,
                            Y = 3
                        },
                        new
                        {
                            Id = 218,
                            Height = 97,
                            Width = 90,
                            X = 12,
                            Y = 2
                        },
                        new
                        {
                            Id = 219,
                            Height = 14,
                            Width = 12,
                            X = 16,
                            Y = 8
                        },
                        new
                        {
                            Id = 220,
                            Height = 14,
                            Width = 32,
                            X = 14,
                            Y = 7
                        },
                        new
                        {
                            Id = 221,
                            Height = 8,
                            Width = 65,
                            X = 20,
                            Y = 11
                        },
                        new
                        {
                            Id = 222,
                            Height = 86,
                            Width = 34,
                            X = 9,
                            Y = 6
                        },
                        new
                        {
                            Id = 223,
                            Height = 68,
                            Width = 40,
                            X = 19,
                            Y = 8
                        },
                        new
                        {
                            Id = 224,
                            Height = 68,
                            Width = 68,
                            X = 4,
                            Y = 20
                        },
                        new
                        {
                            Id = 225,
                            Height = 75,
                            Width = 24,
                            X = 6,
                            Y = 3
                        },
                        new
                        {
                            Id = 226,
                            Height = 41,
                            Width = 23,
                            X = 10,
                            Y = 6
                        },
                        new
                        {
                            Id = 227,
                            Height = 62,
                            Width = 97,
                            X = 5,
                            Y = 16
                        },
                        new
                        {
                            Id = 228,
                            Height = 50,
                            Width = 59,
                            X = 0,
                            Y = 0
                        },
                        new
                        {
                            Id = 229,
                            Height = 92,
                            Width = 96,
                            X = 13,
                            Y = 10
                        },
                        new
                        {
                            Id = 230,
                            Height = 34,
                            Width = 68,
                            X = 0,
                            Y = 4
                        },
                        new
                        {
                            Id = 231,
                            Height = 30,
                            Width = 31,
                            X = 12,
                            Y = 18
                        },
                        new
                        {
                            Id = 232,
                            Height = 91,
                            Width = 64,
                            X = 5,
                            Y = 19
                        },
                        new
                        {
                            Id = 233,
                            Height = 61,
                            Width = 34,
                            X = 3,
                            Y = 5
                        },
                        new
                        {
                            Id = 234,
                            Height = 8,
                            Width = 54,
                            X = 20,
                            Y = 5
                        },
                        new
                        {
                            Id = 235,
                            Height = 71,
                            Width = 51,
                            X = 8,
                            Y = 4
                        },
                        new
                        {
                            Id = 236,
                            Height = 66,
                            Width = 70,
                            X = 16,
                            Y = 18
                        },
                        new
                        {
                            Id = 237,
                            Height = 75,
                            Width = 18,
                            X = 2,
                            Y = 3
                        },
                        new
                        {
                            Id = 238,
                            Height = 77,
                            Width = 94,
                            X = 17,
                            Y = 4
                        },
                        new
                        {
                            Id = 239,
                            Height = 12,
                            Width = 55,
                            X = 20,
                            Y = 16
                        },
                        new
                        {
                            Id = 240,
                            Height = 45,
                            Width = 81,
                            X = 12,
                            Y = 5
                        },
                        new
                        {
                            Id = 241,
                            Height = 34,
                            Width = 84,
                            X = 3,
                            Y = 15
                        },
                        new
                        {
                            Id = 242,
                            Height = 70,
                            Width = 23,
                            X = 1,
                            Y = 17
                        },
                        new
                        {
                            Id = 243,
                            Height = 26,
                            Width = 73,
                            X = 11,
                            Y = 15
                        },
                        new
                        {
                            Id = 244,
                            Height = 9,
                            Width = 21,
                            X = 18,
                            Y = 5
                        },
                        new
                        {
                            Id = 245,
                            Height = 57,
                            Width = 89,
                            X = 9,
                            Y = 1
                        },
                        new
                        {
                            Id = 246,
                            Height = 42,
                            Width = 25,
                            X = 7,
                            Y = 17
                        },
                        new
                        {
                            Id = 247,
                            Height = 40,
                            Width = 76,
                            X = 13,
                            Y = 11
                        },
                        new
                        {
                            Id = 248,
                            Height = 40,
                            Width = 2,
                            X = 17,
                            Y = 20
                        },
                        new
                        {
                            Id = 249,
                            Height = 45,
                            Width = 83,
                            X = 5,
                            Y = 11
                        },
                        new
                        {
                            Id = 250,
                            Height = 98,
                            Width = 82,
                            X = 19,
                            Y = 17
                        },
                        new
                        {
                            Id = 251,
                            Height = 40,
                            Width = 67,
                            X = 1,
                            Y = 10
                        },
                        new
                        {
                            Id = 252,
                            Height = 84,
                            Width = 51,
                            X = 8,
                            Y = 18
                        },
                        new
                        {
                            Id = 253,
                            Height = 58,
                            Width = 69,
                            X = 3,
                            Y = 3
                        },
                        new
                        {
                            Id = 254,
                            Height = 10,
                            Width = 37,
                            X = 8,
                            Y = 0
                        },
                        new
                        {
                            Id = 255,
                            Height = 50,
                            Width = 58,
                            X = 16,
                            Y = 4
                        },
                        new
                        {
                            Id = 256,
                            Height = 100,
                            Width = 87,
                            X = 16,
                            Y = 5
                        },
                        new
                        {
                            Id = 257,
                            Height = 100,
                            Width = 39,
                            X = 6,
                            Y = 16
                        },
                        new
                        {
                            Id = 258,
                            Height = 20,
                            Width = 50,
                            X = 15,
                            Y = 19
                        },
                        new
                        {
                            Id = 259,
                            Height = 24,
                            Width = 59,
                            X = 13,
                            Y = 7
                        },
                        new
                        {
                            Id = 260,
                            Height = 23,
                            Width = 56,
                            X = 11,
                            Y = 8
                        },
                        new
                        {
                            Id = 261,
                            Height = 12,
                            Width = 12,
                            X = 2,
                            Y = 8
                        },
                        new
                        {
                            Id = 262,
                            Height = 40,
                            Width = 15,
                            X = 12,
                            Y = 8
                        },
                        new
                        {
                            Id = 263,
                            Height = 75,
                            Width = 63,
                            X = 13,
                            Y = 20
                        },
                        new
                        {
                            Id = 264,
                            Height = 18,
                            Width = 36,
                            X = 13,
                            Y = 10
                        },
                        new
                        {
                            Id = 265,
                            Height = 61,
                            Width = 47,
                            X = 18,
                            Y = 0
                        },
                        new
                        {
                            Id = 266,
                            Height = 62,
                            Width = 11,
                            X = 2,
                            Y = 19
                        },
                        new
                        {
                            Id = 267,
                            Height = 8,
                            Width = 47,
                            X = 2,
                            Y = 12
                        },
                        new
                        {
                            Id = 268,
                            Height = 96,
                            Width = 88,
                            X = 9,
                            Y = 20
                        },
                        new
                        {
                            Id = 269,
                            Height = 94,
                            Width = 67,
                            X = 3,
                            Y = 8
                        },
                        new
                        {
                            Id = 270,
                            Height = 51,
                            Width = 64,
                            X = 9,
                            Y = 4
                        },
                        new
                        {
                            Id = 271,
                            Height = 80,
                            Width = 16,
                            X = 8,
                            Y = 10
                        },
                        new
                        {
                            Id = 272,
                            Height = 98,
                            Width = 12,
                            X = 15,
                            Y = 12
                        },
                        new
                        {
                            Id = 273,
                            Height = 28,
                            Width = 91,
                            X = 4,
                            Y = 17
                        },
                        new
                        {
                            Id = 274,
                            Height = 6,
                            Width = 31,
                            X = 13,
                            Y = 10
                        },
                        new
                        {
                            Id = 275,
                            Height = 100,
                            Width = 49,
                            X = 15,
                            Y = 1
                        },
                        new
                        {
                            Id = 276,
                            Height = 29,
                            Width = 29,
                            X = 14,
                            Y = 5
                        },
                        new
                        {
                            Id = 277,
                            Height = 77,
                            Width = 69,
                            X = 9,
                            Y = 13
                        },
                        new
                        {
                            Id = 278,
                            Height = 16,
                            Width = 55,
                            X = 10,
                            Y = 6
                        },
                        new
                        {
                            Id = 279,
                            Height = 14,
                            Width = 68,
                            X = 0,
                            Y = 3
                        },
                        new
                        {
                            Id = 280,
                            Height = 44,
                            Width = 20,
                            X = 7,
                            Y = 19
                        },
                        new
                        {
                            Id = 281,
                            Height = 16,
                            Width = 10,
                            X = 10,
                            Y = 5
                        },
                        new
                        {
                            Id = 282,
                            Height = 87,
                            Width = 1,
                            X = 0,
                            Y = 0
                        },
                        new
                        {
                            Id = 283,
                            Height = 20,
                            Width = 98,
                            X = 2,
                            Y = 9
                        },
                        new
                        {
                            Id = 284,
                            Height = 85,
                            Width = 66,
                            X = 15,
                            Y = 19
                        },
                        new
                        {
                            Id = 285,
                            Height = 4,
                            Width = 47,
                            X = 17,
                            Y = 6
                        },
                        new
                        {
                            Id = 286,
                            Height = 16,
                            Width = 5,
                            X = 5,
                            Y = 14
                        },
                        new
                        {
                            Id = 287,
                            Height = 74,
                            Width = 16,
                            X = 16,
                            Y = 10
                        },
                        new
                        {
                            Id = 288,
                            Height = 66,
                            Width = 87,
                            X = 8,
                            Y = 2
                        },
                        new
                        {
                            Id = 289,
                            Height = 49,
                            Width = 86,
                            X = 20,
                            Y = 16
                        },
                        new
                        {
                            Id = 290,
                            Height = 42,
                            Width = 87,
                            X = 11,
                            Y = 15
                        },
                        new
                        {
                            Id = 291,
                            Height = 99,
                            Width = 86,
                            X = 5,
                            Y = 4
                        },
                        new
                        {
                            Id = 292,
                            Height = 26,
                            Width = 55,
                            X = 17,
                            Y = 3
                        },
                        new
                        {
                            Id = 293,
                            Height = 13,
                            Width = 5,
                            X = 5,
                            Y = 19
                        },
                        new
                        {
                            Id = 294,
                            Height = 49,
                            Width = 32,
                            X = 11,
                            Y = 12
                        },
                        new
                        {
                            Id = 295,
                            Height = 80,
                            Width = 90,
                            X = 15,
                            Y = 10
                        },
                        new
                        {
                            Id = 296,
                            Height = 56,
                            Width = 93,
                            X = 16,
                            Y = 19
                        },
                        new
                        {
                            Id = 297,
                            Height = 10,
                            Width = 21,
                            X = 6,
                            Y = 0
                        },
                        new
                        {
                            Id = 298,
                            Height = 80,
                            Width = 80,
                            X = 8,
                            Y = 5
                        },
                        new
                        {
                            Id = 299,
                            Height = 89,
                            Width = 17,
                            X = 3,
                            Y = 10
                        },
                        new
                        {
                            Id = 300,
                            Height = 72,
                            Width = 76,
                            X = 19,
                            Y = 12
                        },
                        new
                        {
                            Id = 301,
                            Height = 14,
                            Width = 71,
                            X = 1,
                            Y = 0
                        },
                        new
                        {
                            Id = 302,
                            Height = 67,
                            Width = 93,
                            X = 11,
                            Y = 7
                        },
                        new
                        {
                            Id = 303,
                            Height = 87,
                            Width = 23,
                            X = 5,
                            Y = 9
                        },
                        new
                        {
                            Id = 304,
                            Height = 54,
                            Width = 8,
                            X = 6,
                            Y = 7
                        },
                        new
                        {
                            Id = 305,
                            Height = 50,
                            Width = 18,
                            X = 18,
                            Y = 0
                        },
                        new
                        {
                            Id = 306,
                            Height = 3,
                            Width = 10,
                            X = 7,
                            Y = 1
                        },
                        new
                        {
                            Id = 307,
                            Height = 10,
                            Width = 48,
                            X = 15,
                            Y = 7
                        },
                        new
                        {
                            Id = 308,
                            Height = 25,
                            Width = 35,
                            X = 15,
                            Y = 10
                        },
                        new
                        {
                            Id = 309,
                            Height = 68,
                            Width = 26,
                            X = 19,
                            Y = 4
                        },
                        new
                        {
                            Id = 310,
                            Height = 5,
                            Width = 74,
                            X = 5,
                            Y = 20
                        },
                        new
                        {
                            Id = 311,
                            Height = 96,
                            Width = 64,
                            X = 19,
                            Y = 6
                        },
                        new
                        {
                            Id = 312,
                            Height = 8,
                            Width = 82,
                            X = 14,
                            Y = 3
                        },
                        new
                        {
                            Id = 313,
                            Height = 20,
                            Width = 46,
                            X = 20,
                            Y = 9
                        },
                        new
                        {
                            Id = 314,
                            Height = 55,
                            Width = 73,
                            X = 1,
                            Y = 20
                        },
                        new
                        {
                            Id = 315,
                            Height = 1,
                            Width = 92,
                            X = 7,
                            Y = 2
                        },
                        new
                        {
                            Id = 316,
                            Height = 34,
                            Width = 16,
                            X = 3,
                            Y = 10
                        },
                        new
                        {
                            Id = 317,
                            Height = 33,
                            Width = 43,
                            X = 18,
                            Y = 12
                        },
                        new
                        {
                            Id = 318,
                            Height = 41,
                            Width = 21,
                            X = 12,
                            Y = 18
                        },
                        new
                        {
                            Id = 319,
                            Height = 18,
                            Width = 32,
                            X = 13,
                            Y = 19
                        },
                        new
                        {
                            Id = 320,
                            Height = 67,
                            Width = 7,
                            X = 9,
                            Y = 11
                        },
                        new
                        {
                            Id = 321,
                            Height = 98,
                            Width = 5,
                            X = 3,
                            Y = 3
                        },
                        new
                        {
                            Id = 322,
                            Height = 47,
                            Width = 52,
                            X = 11,
                            Y = 8
                        },
                        new
                        {
                            Id = 323,
                            Height = 32,
                            Width = 61,
                            X = 18,
                            Y = 20
                        },
                        new
                        {
                            Id = 324,
                            Height = 21,
                            Width = 82,
                            X = 19,
                            Y = 13
                        },
                        new
                        {
                            Id = 325,
                            Height = 6,
                            Width = 58,
                            X = 7,
                            Y = 2
                        },
                        new
                        {
                            Id = 326,
                            Height = 84,
                            Width = 90,
                            X = 8,
                            Y = 4
                        },
                        new
                        {
                            Id = 327,
                            Height = 14,
                            Width = 34,
                            X = 12,
                            Y = 5
                        },
                        new
                        {
                            Id = 328,
                            Height = 77,
                            Width = 100,
                            X = 10,
                            Y = 14
                        },
                        new
                        {
                            Id = 329,
                            Height = 2,
                            Width = 82,
                            X = 12,
                            Y = 3
                        },
                        new
                        {
                            Id = 330,
                            Height = 44,
                            Width = 73,
                            X = 3,
                            Y = 1
                        },
                        new
                        {
                            Id = 331,
                            Height = 3,
                            Width = 34,
                            X = 1,
                            Y = 10
                        },
                        new
                        {
                            Id = 332,
                            Height = 23,
                            Width = 48,
                            X = 19,
                            Y = 16
                        },
                        new
                        {
                            Id = 333,
                            Height = 89,
                            Width = 99,
                            X = 14,
                            Y = 0
                        },
                        new
                        {
                            Id = 334,
                            Height = 13,
                            Width = 61,
                            X = 18,
                            Y = 18
                        },
                        new
                        {
                            Id = 335,
                            Height = 63,
                            Width = 81,
                            X = 11,
                            Y = 4
                        },
                        new
                        {
                            Id = 336,
                            Height = 47,
                            Width = 35,
                            X = 16,
                            Y = 19
                        },
                        new
                        {
                            Id = 337,
                            Height = 74,
                            Width = 39,
                            X = 0,
                            Y = 7
                        },
                        new
                        {
                            Id = 338,
                            Height = 33,
                            Width = 12,
                            X = 0,
                            Y = 12
                        },
                        new
                        {
                            Id = 339,
                            Height = 30,
                            Width = 47,
                            X = 17,
                            Y = 14
                        },
                        new
                        {
                            Id = 340,
                            Height = 62,
                            Width = 22,
                            X = 3,
                            Y = 12
                        },
                        new
                        {
                            Id = 341,
                            Height = 4,
                            Width = 34,
                            X = 3,
                            Y = 2
                        },
                        new
                        {
                            Id = 342,
                            Height = 67,
                            Width = 70,
                            X = 7,
                            Y = 10
                        },
                        new
                        {
                            Id = 343,
                            Height = 26,
                            Width = 98,
                            X = 10,
                            Y = 9
                        },
                        new
                        {
                            Id = 344,
                            Height = 97,
                            Width = 59,
                            X = 2,
                            Y = 5
                        },
                        new
                        {
                            Id = 345,
                            Height = 15,
                            Width = 99,
                            X = 10,
                            Y = 3
                        },
                        new
                        {
                            Id = 346,
                            Height = 85,
                            Width = 38,
                            X = 10,
                            Y = 17
                        },
                        new
                        {
                            Id = 347,
                            Height = 42,
                            Width = 67,
                            X = 7,
                            Y = 20
                        },
                        new
                        {
                            Id = 348,
                            Height = 44,
                            Width = 73,
                            X = 11,
                            Y = 6
                        },
                        new
                        {
                            Id = 349,
                            Height = 26,
                            Width = 45,
                            X = 3,
                            Y = 7
                        },
                        new
                        {
                            Id = 350,
                            Height = 3,
                            Width = 27,
                            X = 16,
                            Y = 7
                        },
                        new
                        {
                            Id = 351,
                            Height = 59,
                            Width = 20,
                            X = 3,
                            Y = 9
                        },
                        new
                        {
                            Id = 352,
                            Height = 70,
                            Width = 37,
                            X = 15,
                            Y = 20
                        },
                        new
                        {
                            Id = 353,
                            Height = 13,
                            Width = 48,
                            X = 10,
                            Y = 11
                        },
                        new
                        {
                            Id = 354,
                            Height = 98,
                            Width = 30,
                            X = 11,
                            Y = 18
                        },
                        new
                        {
                            Id = 355,
                            Height = 14,
                            Width = 76,
                            X = 15,
                            Y = 3
                        },
                        new
                        {
                            Id = 356,
                            Height = 72,
                            Width = 9,
                            X = 15,
                            Y = 14
                        },
                        new
                        {
                            Id = 357,
                            Height = 15,
                            Width = 7,
                            X = 17,
                            Y = 2
                        },
                        new
                        {
                            Id = 358,
                            Height = 43,
                            Width = 17,
                            X = 17,
                            Y = 7
                        },
                        new
                        {
                            Id = 359,
                            Height = 71,
                            Width = 53,
                            X = 6,
                            Y = 17
                        },
                        new
                        {
                            Id = 360,
                            Height = 21,
                            Width = 73,
                            X = 10,
                            Y = 1
                        },
                        new
                        {
                            Id = 361,
                            Height = 32,
                            Width = 1,
                            X = 12,
                            Y = 19
                        },
                        new
                        {
                            Id = 362,
                            Height = 70,
                            Width = 52,
                            X = 8,
                            Y = 5
                        },
                        new
                        {
                            Id = 363,
                            Height = 77,
                            Width = 82,
                            X = 3,
                            Y = 6
                        },
                        new
                        {
                            Id = 364,
                            Height = 100,
                            Width = 17,
                            X = 2,
                            Y = 18
                        },
                        new
                        {
                            Id = 365,
                            Height = 17,
                            Width = 75,
                            X = 4,
                            Y = 16
                        },
                        new
                        {
                            Id = 366,
                            Height = 82,
                            Width = 74,
                            X = 3,
                            Y = 3
                        },
                        new
                        {
                            Id = 367,
                            Height = 98,
                            Width = 41,
                            X = 6,
                            Y = 1
                        },
                        new
                        {
                            Id = 368,
                            Height = 81,
                            Width = 4,
                            X = 20,
                            Y = 5
                        },
                        new
                        {
                            Id = 369,
                            Height = 80,
                            Width = 26,
                            X = 5,
                            Y = 1
                        },
                        new
                        {
                            Id = 370,
                            Height = 77,
                            Width = 71,
                            X = 5,
                            Y = 9
                        },
                        new
                        {
                            Id = 371,
                            Height = 25,
                            Width = 28,
                            X = 7,
                            Y = 17
                        },
                        new
                        {
                            Id = 372,
                            Height = 41,
                            Width = 21,
                            X = 12,
                            Y = 16
                        },
                        new
                        {
                            Id = 373,
                            Height = 12,
                            Width = 69,
                            X = 14,
                            Y = 20
                        },
                        new
                        {
                            Id = 374,
                            Height = 77,
                            Width = 26,
                            X = 3,
                            Y = 7
                        },
                        new
                        {
                            Id = 375,
                            Height = 89,
                            Width = 5,
                            X = 3,
                            Y = 14
                        },
                        new
                        {
                            Id = 376,
                            Height = 50,
                            Width = 76,
                            X = 13,
                            Y = 12
                        },
                        new
                        {
                            Id = 377,
                            Height = 59,
                            Width = 90,
                            X = 2,
                            Y = 2
                        },
                        new
                        {
                            Id = 378,
                            Height = 49,
                            Width = 42,
                            X = 2,
                            Y = 0
                        },
                        new
                        {
                            Id = 379,
                            Height = 92,
                            Width = 79,
                            X = 19,
                            Y = 2
                        },
                        new
                        {
                            Id = 380,
                            Height = 23,
                            Width = 42,
                            X = 3,
                            Y = 9
                        },
                        new
                        {
                            Id = 381,
                            Height = 67,
                            Width = 80,
                            X = 6,
                            Y = 3
                        },
                        new
                        {
                            Id = 382,
                            Height = 61,
                            Width = 18,
                            X = 13,
                            Y = 14
                        },
                        new
                        {
                            Id = 383,
                            Height = 4,
                            Width = 32,
                            X = 9,
                            Y = 8
                        },
                        new
                        {
                            Id = 384,
                            Height = 16,
                            Width = 37,
                            X = 18,
                            Y = 18
                        },
                        new
                        {
                            Id = 385,
                            Height = 18,
                            Width = 9,
                            X = 0,
                            Y = 10
                        },
                        new
                        {
                            Id = 386,
                            Height = 72,
                            Width = 23,
                            X = 9,
                            Y = 0
                        },
                        new
                        {
                            Id = 387,
                            Height = 9,
                            Width = 100,
                            X = 13,
                            Y = 12
                        },
                        new
                        {
                            Id = 388,
                            Height = 59,
                            Width = 18,
                            X = 9,
                            Y = 19
                        },
                        new
                        {
                            Id = 389,
                            Height = 22,
                            Width = 3,
                            X = 3,
                            Y = 14
                        },
                        new
                        {
                            Id = 390,
                            Height = 19,
                            Width = 17,
                            X = 14,
                            Y = 1
                        },
                        new
                        {
                            Id = 391,
                            Height = 5,
                            Width = 56,
                            X = 12,
                            Y = 17
                        },
                        new
                        {
                            Id = 392,
                            Height = 56,
                            Width = 62,
                            X = 6,
                            Y = 6
                        },
                        new
                        {
                            Id = 393,
                            Height = 39,
                            Width = 15,
                            X = 19,
                            Y = 12
                        },
                        new
                        {
                            Id = 394,
                            Height = 93,
                            Width = 5,
                            X = 17,
                            Y = 9
                        },
                        new
                        {
                            Id = 395,
                            Height = 44,
                            Width = 31,
                            X = 19,
                            Y = 8
                        },
                        new
                        {
                            Id = 396,
                            Height = 27,
                            Width = 95,
                            X = 12,
                            Y = 4
                        },
                        new
                        {
                            Id = 397,
                            Height = 32,
                            Width = 29,
                            X = 14,
                            Y = 4
                        },
                        new
                        {
                            Id = 398,
                            Height = 63,
                            Width = 49,
                            X = 15,
                            Y = 18
                        },
                        new
                        {
                            Id = 399,
                            Height = 19,
                            Width = 1,
                            X = 10,
                            Y = 13
                        },
                        new
                        {
                            Id = 400,
                            Height = 17,
                            Width = 29,
                            X = 4,
                            Y = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
